typography_spectrum: 0.44573381858112493
color:
  saturation: 0.6713097720405106
  brandStrength: 0.31311783324502923
  rhythmicContrast: 0.5717756238962421
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  lightness: 0.8214288871304712
opengraph:
  image: null
layout_spectrum: 0.45643838966947675
analytics:
  google: UA-41772503-1
author:
  name: Marc Orro
  email: marc@orro.me
  url: Marc.Orro.me
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/52017e6d-800f-4fd0-a571-096474edfeae.png
name: Marc Orro
navigation:
  - name: "\uD83D\uDCA5  Experiments"
    url: 'http://experiments.orro.me'
    type: external
  - name: "\uD83D\uDC40  Projects"
    url: 'http://projects.orro.me'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b1e7552-cb7b-4c7d-99be-52acb2945027.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Your new AI designer
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/540dd6f1-ee04-4f8f-a8e3-20ec7649ccf7.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/540dd6f1-ee04-4f8f-a8e3-20ec7649ccf7.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f96b8678-758a-4467-b8c3-99f2a106487d.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f96b8678-758a-4467-b8c3-99f2a106487d.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  He’s young, he’s learning, but he already designed hundreds of web and mobile
  apps including this one. 24/7 he’s experimenting, figuring out what works &
  what doesn’t.  He's quirky, but will never ghost you, never charge more, never
  miss a deadline, never cower to your demands for a bigger logo.
purpose:
  - type: contact
    url: 'mailto:marc@orro.me'
    label: Drop him a line
  - type: contact
    url: 'tel:+61(0)426266776'
    label: "\uD83D\uDCDE or give me a buzz"
github: true
