typography_spectrum: 0.44573381858112493
color:
  saturation: 0.6713097720405106
  brandStrength: 0.31311783324502923
  rhythmicContrast: 0.5717756238962421
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  lightness: 0.8214288871304712
opengraph:
  image: null
layout_spectrum: 0.45643838966947675
analytics:
  google: UA-41772503-1
author:
  name: Marc Orro
  email: marc@orro.me
  url: Marc.Orro.me
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/52017e6d-800f-4fd0-a571-096474edfeae.png
name: Marc Orro
navigation:
  - name: "\uD83D\uDCA5  Experiments"
    url: 'http://experiments.orro.me'
    type: external
  - name: "\uD83D\uDC40  Projects"
    url: 'http://projects.orro.me'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b1e7552-cb7b-4c7d-99be-52acb2945027.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
content: []
description: ' This site is built using Artificial Intelligence. I''m working to improve it :)'
purpose:
  - type: contact
    url: 'mailto:marc@orro.me'
    label: "\uD83D\uDCDD Drop me a line"
  - type: contact
    url: 'tel:+61(0)426266776'
    label: "\uD83D\uDCDE or give me a buzz"
github: true
