typography_spectrum: 0.5628604704305752
color:
  brandStrength: 0.9278241306098898
  lightness: 0.9696343557308843
  saturation: 0.6864054492372319
  rhythmicContrast: 0.5544266433238356
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c08c231a-0803-4734-9ece-f17b99099a21.png
layout_spectrum: 0.12132219809208913
analytics:
  google: UA-41772503-1
author:
  name: Marc Orro
  email: marc@orro.me
  url: Marc.Orro.me
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d01d0025-3fa7-4b14-81e2-72e7da60abc6.png
name: Marc Orro
navigation:
  - name: Live Projects
    id: c58b738e-f4df-429c-b03f-3ec73507472d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e4efeddf-b47b-4e7f-a273-b7b6f15747b1.png
title: Marc Orro
content: []
description: Brand Manager & Digital Strategist
purpose:
  - type: contact
    url: 'mailto:marc@orro.me'
    label: Drop me a line
  - type: contact
    url: 'tel:+61(0)426266776'
    label: or Give me a buzz!
